[CI] Migrate run scripts to team scripts

diff --git a/.ci/run-tests b/.ci/run-tests
--- a/.ci/run-tests
+++ b/.ci/run-tests
@@ -1,42 +1,71 @@
 #!/usr/bin/env bash
-
 #
-# Runs the client tests via Docker with the expectation that the required
-# environment variables have already been exported before running this script.
-#
-# The required environment variables include:
-#
-#   - $TEST_SUITE
-#
+# Version 1.1
+# - Moved to .ci folder and seperated out `run-repository.sh`
+# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products
 
-set -eo pipefail
+if [[ -z $ELASTICSEARCH_VERSION ]]; then
+  echo -e "\033[31;1mERROR:\033[0m Required environment variable [ELASTICSEARCH_VERSION] not set\033[0m"
+  exit 1
+fi
+set -euxo pipefail
 
-export RUBY_TEST_VERSION=${RUBY_TEST_VERSION:-2.6.1}
-export ELASTICSEARCH_VERSION=${ELASTICSEARCH_VERSION:-8.0.0-SNAPSHOT}
-export SINGLE_TEST=${SINGLE_TEST}
+TEST_SUITE=${TEST_SUITE-oss}
+RUNSCRIPTS=${RUNSCRIPTS-}
+NODE_NAME=instance
 
-set +x
-export VAULT_TOKEN=$(vault write -field=token auth/approle/login role_id="$VAULT_ROLE_ID" secret_id="$VAULT_SECRET_ID")
-unset VAULT_ROLE_ID VAULT_SECRET_ID VAULT_TOKEN
-set -x
+elasticsearch_image=elasticsearch
+elasticsearch_url=https://elastic:changeme@${NODE_NAME}:9200
+if [[ $TEST_SUITE != "xpack" ]]; then
+  elasticsearch_image=elasticsearch-${TEST_SUITE}
+  elasticsearch_url=http://${NODE_NAME}:9200
+fi
 
 function cleanup {
-  docker container rm --force --volumes elasticsearch > /dev/null 2>&1 || true
-  docker container rm --force --volumes elasticsearch-ruby > /dev/null 2>&1 || true
-  docker network rm esnet > /dev/null
+  status=$?
+  set +x
+  ELASTICSEARCH_VERSION=${elasticsearch_image}:${ELASTICSEARCH_VERSION} \
+    NODE_NAME=${NODE_NAME} \
+    NETWORK_NAME=elasticsearch \
+    CLEANUP=true \
+    bash ./.ci/run-elasticsearch.sh
+  # Report status and exit
+  if [[ "$status" == "0" ]]; then
+    echo -e "\n\033[32;1mSUCCESS run-tests\033[0m"
+    exit 0
+  else
+    echo -e "\n\033[31;1mFAILURE during run-tests\033[0m"
+    exit ${status}
+  fi
 }
-
 trap cleanup EXIT
 
-# create network and volume
-docker network create esnet
+(
+  echo -e "\033[1m>>>>> Start [$ELASTICSEARCH_VERSION container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
 
-# create client image
-docker build \
-  --file .ci/Dockerfile \
-  --tag elastic/elasticsearch-ruby \
-  --build-arg RUBY_TEST_VERSION=${RUBY_TEST_VERSION} \
-  .
+  ELASTICSEARCH_VERSION=${elasticsearch_image}:${ELASTICSEARCH_VERSION} \
+    NODE_NAME=${NODE_NAME} \
+    NETWORK_NAME=elasticsearch \
+    DETACH=true \
+    bash .ci/run-elasticsearch.sh
 
+  if [[ -n "$RUNSCRIPTS" ]]; then
+    for RUNSCRIPT in ${RUNSCRIPTS//,/ } ; do
+      echo -e "\033[1m>>>>> Running run-$RUNSCRIPTS.sh >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
+      ELASTICSEARCH_CONTAINER=${elasticsearch_image}:${ELASTICSEARCH_VERSION} \
+        NETWORK_NAME=elasticsearch \
+        NODE_NAME=${RUNSCRIPT} \
+        ELASTICSEARCH_URL=${elasticsearch_url} \
+        DETACH=true \
+        bash .ci/run-${RUNSCRIPT}.sh
+    done
+  fi
 
-sh .ci/docker/run-${TEST_SUITE}
+  echo -e "\033[1m>>>>> Repository specific tests >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
+
+  ELASTICSEARCH_CONTAINER=${elasticsearch_image}:${ELASTICSEARCH_VERSION} \
+    NETWORK_NAME=elasticsearch \
+    NODE_NAME=${NODE_NAME} \
+    ELASTICSEARCH_URL=${elasticsearch_url} \
+    bash .ci/run-repository.sh
+)
